blank_issues_enabled: true
contact_links:
  - name: ğŸ› ï¸ API issue (api.modrinth.com)
    about: Report an issue regarding the Modrinth API. Problem is releated to Modrinth, this will redirect you to Modrinth issues.
    url: https://github.com/modrinth/code/issues
  - name: ğŸŒ Website bug (modrinth.com)
    about: Report an issue on the Modrinth website. Problem is releated to Modrinth, this will redirect you to Modrinth issues.
    url: https://github.com/modrinth/code/issues
  - name: ğŸ«¶ Support Portal
    about: Get support using through our portal.
    url: https://support.modrinth.com
  - name: ğŸ’¬ Chat
    about: Join our Discord server to chat about Modrinth.
    url: https://discord.modrinth.com
  - name: ğŸ›£ï¸ Roadmap
    about: View our Roadmap. Please do not open issues for items on our roadmap.
    url: https://roadmap.modrinth.com
  - name: ğŸ“š Documentation
    about: Useful documentation about Modrinth's API
    url: https://docs.modrinth.com
